### ISSUE TITLE
Bug in the EUF interpolation

### ISSUE THREAD

**Issue by sepideha** [usi-verification-and-security/opensmt#231]
When running UpProver in EUF encoding for the attached example, an exception is thrown in `getSingleInterpolant(interpolants, mask)`. 

Up to OpenSMT version 555c592f the verification was successful, but it seems after d1592f50 onwards verification of the example crashes.

- Example: see [here](https://gist.github.com/sepideha/a803d4497288b54cfd538cfa2ce6f83a)

- Exact command line resulting in the issue: run in UpProver (4cf51de8 or any older version): `./upprover --logic qfuf --bootstrapping ex7-v5.c`

- What behaviour did you expect: UNSAT in EUF with generated interpolants

- What happened instead: exception thrown in `getSingleInterpolant(interpolants, mask)` with message `libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found`

P.S. I also tried OpenSMT ec7cf31c but the following exception is thrown in the same method `libc++abi.dylib: terminating with uncaught exception of type OsmtInternalException: No color detected for term`

**Comment by blishko** [comment]
[Here](https://gist.github.com/blishko/34c5331646af00225fe70f7832e589c8) is an SMT-LIB file that shows this problem.

**Comment by blishko** [comment]
And here is the simplified version:
```
(set-option :produce-interpolants 1)
(set-logic QF_UF)
(declare-sort U 0)
(declare-fun f (U U) U)
(declare-fun P (U) Bool)
(declare-fun x () U)
(declare-fun y () U)

(declare-fun r1 () U)
(declare-fun r2 () U)
(declare-fun a1 () U)
(declare-fun a2 () U)
(declare-fun b1 () U)
(declare-fun b2 () U)

(assert (! (and (= r1 (f a1 b1)) (= r2 (f a2 b2)))
:named B))

(assert (! (and (P (f x y)) (= a1 x) (= b1 y) (= a2 x) (= b2 y) (not (= r1 r2)))
:named A))


(check-sat)
(get-interpolants A B)
```

**Comment by blishko** [comment]
This example is interesting because it suggests there is potentially some redundancy in the witness of unsatisfiability used for interpolation (namely `CGraph` structure). In this case, it contains the redundant node `f(x,y)` which is not necessary to witness the unsatisfiability.
Here, instead of deriving that `f(a1, b1)` is in the same equivalence class with `f(a2,b2)` by congruence, because `a1 ~ a2` and `b1 ~ b2`, the explanation contains a redundant path through `f(x,y)`.
The explanation found here is that `f(a1,b1) ~ f(a2,b2)` because both are equivalent to `f(x,y)` through congruence.
