### ISSUE TITLE
Soundness bug in parallel opensmt (SMTS)

### ISSUE THREAD

**Issue by aehyvari** [usi-verification-and-security/opensmt#548]
In some cases the parallel opensmt (SMTS) implementation reports satisfiable instances as unsatisfiable.  The sequential solver is not affected by this bug.  At the moment it seems that this is coming from the code enabled with `PARALLEL=ON` in opensmt.  Auxiliary variables being communicated between the solvers can sometimes be mapped to incorrect terms.

**Comment by aehyvari** [comment]
The initial part of the fix is in #547

**Comment by MasoudAsadzade** [comment]
A comparison of sequential and parallel version on QF_LIA after soundness bug was fixed.
*Part of the fix is in https://github.com/usi-verification-and-security/opensmt/pull/547

![non-incremental-QF-40MinuteMaster-2022-07-04_vs_cqIncremental-2022-08-21](https://user-images.githubusercontent.com/17990258/186912349-4780bc99-81fb-42e8-a7cb-ecbe00cc3b0b.png)
![non-incremental-QF-40MinuteMaster-2022-07-04_vs_cqIncrementalLemmaSharing-2022-08-19](https://user-images.githubusercontent.com/17990258/186912352-0916cd0d-9293-4041-8761-5bf1030f3852.png)
